import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NFTBox from "@/components/BaseNFT";
import ConnectButton from "@/components/ConnectButton";
import TokenBar from "@/components/TokenBar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SubLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <RootLayout>
    <div>
        {/* <TokenBar /> */}
        {children}
    </div>
    // </RootLayout>
  );
}
