import type { Metadata } from "next";
// import Head from 'next/head';
import { Inter } from "next/font/google";
import './globals.css'

import NFTBox from "@/components/BaseNFT";
import ConnectButton from "@/components/ConnectButton";

import { Web3Modal } from '../context/web3modal'
import AppBar from "@/components/ui/appbar";
import { TagFilter } from "@/components/TagFilter";
import SearchBar from "@/components/ui/SearchBar";
import NavMenu from "@/components/NavMenu";
import { OrderByFilter } from "@/components/OrderByFilter";
import TagList from "@/components/TagListWithContext";
import NFTsHeader from "@/components/NFTsHeader";

import { ApolloProvider } from '@apollo/client';
import client from '../lib/apollo-client';

import { Toaster } from "@/components/ui/toaster"
import { NFTperRowProvider } from "@/context/NFTperRowContext";
import Structure from "@/components/Structure";
import { ApolloWrapper } from "./ApolloWrapper";



export const dynamic = 'force-dynamic';
export const fetchCache = 'default-no-store';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add meta tags or other head elements here */}
      </head>
      <body className={`${inter.className} flex-grow overflow-y-auto pb-16 md:pb-0`}>
        <div>
          <Structure>
            <ApolloWrapper>{children}</ApolloWrapper>
          </Structure>
        </div>
      </body>
    </html>
  );
}